max_steps = 10000
seq_len = 8196
max_async_level = 4

[deployment]
num_train_gpus = 4
num_infer_gpus = 4

[model]
name = "Qwen/Qwen3-8B"

[wandb]
project = "api-adapter"  # matches WANDB_PROJECT in api-adapter/.env
name = "test-prime-rl-ifbench-4b-lora-8gpu-v8"

[orchestrator]
batch_size = 2048
rollouts_per_example = 64
max_off_policy_steps = 16
oversampling_factor = 1


[orchestrator.train.sampling]
max_completion_tokens = 4096
temperature = 1.4

[[orchestrator.train.env]]
id = "ifbench_api_adapter@local"

[orchestrator.buffer]
#  - Thresholds: permanently move the example out of the sampling pool (one-way door)
#  - Online difficulty filtering: drop the rollouts from this batch, but the example stays in the pool and gets sampled again next step
easy_threshold = 1.0  # we dont want to waste training cycles on easy problems because we already know how to solve them 
easy_fraction = 0.3  # but we also want to make sure that we dont forget them, and hence when we restart training, we will have a easy_fraction of 0.3 in the pool again, and then decide later if they are still easy.
online_difficulty_filtering = true


[trainer.optim]
lr = 1e-6
weight_decay = 0.001
type = "adamw"

[trainer.model]
fsdp_cpu_offload = false
dp_replicate = 2  # full model on each GPU, no sharding — only all-reduce LoRA gradients
fused_lm_head_token_chunk_size = "auto"  # chunked loss computation to reduce memory

[trainer.model.compile]  # torch.compile for kernel fusion

[trainer.model.lora]
rank = 32
alpha = 64.0
target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]

[ckpt]
interval = 200
resume_step = -1

[inference.parallel]
dp = 1
tp = 4
